"""add mode column

Revision ID: 3ca6eb95f75d
Revises: 028b3319860a
Create Date: 2025-10-22 23:20:13.597252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ca6eb95f75d'
down_revision: Union[str, Sequence[str], None] = '028b3319860a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesession', sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesession', 'mode')
    # ### end Alembic commands ###
